### ISSUE TITLE
flapdoodle can't start mongo ( Could not start process: <EOF>)

### ISSUE THREAD

**Issue by razorree** [michaelmosmann/embedmongo.flapdoodle.de#13]
Caused by: java.io.IOException: Could not start process: <EOF>
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:79)
        at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:116)
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
        at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
        at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108)

after short debugging i can see, that pidFile (in AbstractProcess) has path:
C:\Users\<user>\AppData\Local\Temp\extract-a6b69aa1-8ef6-4c1d-8ddd-840748849e84mongod.pid

and also there is executable with similar path: extract-a6b69aa1-8ef6-4c1d-8ddd-840748849e84mongod.exe

when i try to run in (from command line or windows shell) OS complains about
libeay32.dll and ssleay32.dll
not found.

Is it a real problem for this exception?  (and failing to run embed mongo)

after copying these two files manually to temp folder, service works.

(newest version 2.1.1)

**Comment by michaelmosmann** [comment]
please create an issue at https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo if needed.. will close this.
